### ISSUE TITLE
No longer available via Homebrew?

### ISSUE THREAD

**Issue by holograph** [felicianotech/sonar#153]
The readme recommends installing via `brew install sonar`, however that is now an alias for SonarQube. Going through the results on `brew search sonar` didn't bring anything up. Is Sonar still available via Homebrew?

**Comment by FelicianoTech** [comment]
Yes but it's a tap. I need to update the instructions. This is what you should run:

`brew install felicianotech/tap/sonar`

Let's keep this issue open until I update the instructions. Thank you for the call out.

**Comment by holograph** [comment]
How about I'll do some legwork and send you a pull request :-)

**Comment by holograph** [comment]
See #154
